# Generated by Django 2.1.8 on 2019-09-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
