# Generated by Django 2.1.8 on 2019-09-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190927_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
