# Generated by Django 2.1.5 on 2019-07-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='foucs',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
