# Generated by Django 2.1.2 on 2018-11-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
