# Generated by Django 2.1.2 on 2018-11-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcomepage',
            old_name='conent',
            new_name='content',
        ),
    ]
