# Generated by Django 2.1.5 on 2019-07-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='affiliation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
