# Generated by Django 2.1.2 on 2018-12-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20181127_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.CharField(default='na', max_length=50),
            preserve_default=False,
        ),
    ]
