# Generated by Django 2.1.2 on 2018-11-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_solvedchallenge_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='correct_flags',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.AlterField(
            model_name='team',
            name='solved',
            field=models.ManyToManyField(related_name='team', to='teams.SolvedChallenge'),
        ),
    ]
